start-dropbox-nixos -> bin/start-dropbox-nixos

diff --git a/bin/start-dropbox-nixos b/bin/start-dropbox-nixos
--- a/bin/start-dropbox-nixos
+++ b/bin/start-dropbox-nixos
@@ -21,7 +21,7 @@ fi
 # 'command -v xyz' describes xyz but does not run it, allowing us to see
 # whether the command exists (dropbox is installed).
 # Piping to /dev/null means we don't have to see the description.
-if command -v dropbox > /dev/null; then
+if command -v dropbox >/dev/null; then
   # TODO: is dropbox started on system startup?
   # Note that we don't want to start multiple instances.
   # Take a look at this: https://nixos.wiki/wiki/Dropbox
@@ -30,9 +30,9 @@ if command -v dropbox > /dev/null; then
   # NOTE - Before installing dropbox with this command:
   #     nix-env -iA nixos.dropbox
   # it might be necessary to be logged into the dropbox website.
- 
+
   # If dropbox isn't running, start it
-  if [[ $(pgrep -c dropbox) -eq 0 ]] ; then
+  if [[ $(pgrep -c dropbox) -eq 0 ]]; then
     if nix-env -q "dropbox-cli.*"; then
       # dropbox was installed as nixos.dropbox-cli
 
@@ -44,14 +44,19 @@ if command -v dropbox > /dev/null; then
       if [ "$(dropbox status | head -n 1)" == "Dropbox isn't running!" ]; then
         cd "$DROPBOX_DIR"
         # all this extra code is to start it without any messages
-        $(nohup dropbox start >> "$HOME"/.start-dropbox-nixos.log 2>&1 &) > /dev/null
+        $(nohup dropbox start >>"$HOME"/.start-dropbox-nixos.log 2>&1 &) >/dev/null
         cd "$INITIAL_DIR"
       fi
     else
       # assume dropbox was installed as nixos.dropbox
 
       # all this extra code is to start it without any messages
-      $(nohup dropbox >> "$HOME"/.start-dropbox-nixos.log 2>&1 &) > /dev/null
+      $(nohup dropbox >>"$HOME"/.start-dropbox-nixos.log 2>&1 &) >/dev/null
     fi
   fi
+  if [[ $(pgrep -c dropbox) -eq 0 ]]; then
+    echo "dropbox unable to start" 1>&2
+  fi
+else
+  echo "dropbox command not available. Is it installed?" 1>&2
 fi
